# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Read SCID to ConfigMap for PCE

on:
 pull_request:
   paths:
   - '**'

# on:
#   push:
#     branches:
#       - master

jobs:
  deploy-scid-configmap:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Master Branch
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Run script to generate SCID-Infos json file
        run: |
          ./.github/workflows/pce-scid-scripts/script.py

      - name: Generate SCID-ConfigMap Mainfest file
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create configmap -n pcaas pcaas-scid-configuration --from-file scidInfos.json --dry-run -o yaml > scidconfigmap.json

      - name: Deploy SCID-ConfigMap in PCaaS Namespace
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f scidconfigmap.json
